- hosts: localhost
  become: true

  vars:
    cloudwatch_agent_dynamic_patterns:
      - base_path: "/var/www/bo-fm/logs"
        patterns: ["app*.log", "error*.log"]
        log_group_prefix: "/aws/drupal-fm"
        timestamp_format: "%Y-%m-%d %H:%M:%S"

  pre_tasks:
    - name: Discover logs from dynamic patterns
      find:
        paths: "{{ item.base_path }}"
        patterns: "{{ item.patterns }}"
        recurse: yes
        file_type: file
      register: found_logs
      loop: "{{ cloudwatch_agent_dynamic_patterns }}"
      loop_control:
        label: "{{ item.base_path }}"

    - name: Flatten dynamic log list
      set_fact:
        dynamic_log_files: "{{ found_logs.results | map(attribute='files') | flatten | list }}"

    - name: Generate structured log entries for CloudWatch Agent
      set_fact:
        dynamic_log_files_structured: >-
          {{
            dynamic_log_files_structured | default([]) + [
              {
                "file_path": item,
                "log_group_name": cloudwatch_agent_dynamic_patterns[0].log_group_prefix ~ '/' ~ (item | basename),
                "timestamp_format": cloudwatch_agent_dynamic_patterns[0].timestamp_format
              }
            ]
          }}
      loop: "{{ dynamic_log_files | map(attribute='path') | list }}"
      loop_control:
        label: "{{ item }}"
        
    - name: Merge static and dynamic logs
      set_fact:
        cloudwatch_agent_log_files: "{{ cloudwatch_agent_log_files | default([]) + dynamic_log_files_structured }}"

  roles:
    - cloudwatch_agent
